### ISSUE TITLE
Incompatible with Guard 2.0 (was: guard init elixir failing)

### ISSUE THREAD

**Issue by DevL** [webcoyote/guard-elixir#2]
**UPDATE** Locking guard to a version below 2.0 made things work again.

**UPDATE 2:** There seems to be a fix in https://github.com/os6sense/guard-elixir but unfortunately that hasn't been submitted as a pull request to the upstream (this) repo. @os6sense - would you be willing to either submit a pull request or be open to wokring on a proper successor fork with updated gems posted to Rubygems?
### Steps to reproduce:
1. Add guard-elixir to the Gemfile
2. bundle
3. run `guard init elixir`

```
$ guard init elixir
10:42:48 - ERROR - Could not load 'guard/elixir' or '~/.guard/templates/elixir' or find class Guard::Elixir
10:42:48 - ERROR - Error is: No such file or directory @ rb_sysopen - /Users/devl/.guard/templates/elixir
```

List of gems and their version.

```
*** LOCAL GEMS ***

bundler (1.8.5)
celluloid (0.16.0)
coderay (1.1.0)
ffi (1.9.8)
formatador (0.2.5)
guard (2.12.5)
guard-elixir (0.0.2)
hitimes (1.2.2)
listen (2.9.0)
lumberjack (1.0.9)
method_source (0.8.2)
nenv (0.2.0)
notiffany (0.0.6)
pry (0.10.1)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
shellany (0.0.1)
slop (3.6.0)
thor (0.19.1)
timers (4.0.1)
```

Adding the Guardfile by hand and running `guard` yields the following error.

```
devl$ bundle exec guard
10:48:01 - ERROR - Could not load 'guard/elixir' or find class Guard::Elixir
10:48:01 - ERROR - Error is: cannot load such file -- guard/guard
10:48:01 - ERROR - /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-elixir-0.0.2/lib/guard/elixir.rb:2:in `require'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-elixir-0.0.2/lib/guard/elixir.rb:2:in `<top (required)>'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/plugin_util.rb:105:in `require'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/plugin_util.rb:105:in `rescue in plugin_class'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/plugin_util.rb:97:in `plugin_class'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/plugin_util.rb:56:in `initialize_plugin'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/internals/plugins.rb:26:in `add'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/dsl.rb:185:in `block in guard'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `each'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `guard'
> [#] /Users/devl/Dev/elixir/guardsafe/Guardfile:1:in `evaluate'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `instance_eval'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `evaluate'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard.rb:134:in `_evaluate'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard.rb:49:in `setup'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/commander.rb:32:in `start'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/cli.rb:113:in `start'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] /Users/devl/.rvm/gems/ruby-2.2.1/gems/guard-2.12.5/bin/_guard-core:11:in `<main>'
10:48:01 - ERROR - Invalid Guardfile, original error is:
> [#]
> [#] Could not load class: "Elixir",
> [#] backtrace:
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/plugin_util.rb:57:in `initialize_plugin'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/internals/plugins.rb:26:in `add'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:185:in `block in guard'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `each'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `guard'
> [#]   (dsl)> ./Guardfile:1:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `instance_eval'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard.rb:134:in `_evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard.rb:49:in `setup'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/commander.rb:32:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli.rb:113:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:32:in `execute'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.12.5/bin/_guard-core:11:in `<main>'
```

**Comment by joevandyk** [comment]
This would be nice to resolve
